apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-app-backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
  annotations:
    # This also supports bitbucket/xxx/yyy
    circleci.com/project-slug: github/my-org/my-repo
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
